const puppeteer = require('puppeteer');
const readline = require('readline');
const fs = require('fs');

const lineReader = require('line-reader');
const { exit } = require('process');
//Promise = require('bluebird');

urlPathGlobal = "scraper/producturls.txt"

var urlArray = [];

/*
lineReader.eachLine(urlPathGlobal, function(line) {
    urlArray.push(line);
});*/

async function run () {
    //browser on?
        //const browser = await puppeteer.launch({headless: false});
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.setViewport({width: 3840, height: 2160});

    await page.setDefaultNavigationTimeout(0);
    await page.setDefaultTimeout(0);

    async function waitForCheckoutPage() {
        try {
            await page.waitForSelector('html > body > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(2) > main > div > div:nth-of-type(2) > form > div:nth-of-type(2) > div:nth-of-type(2) > div > div > div:nth-of-type(4) > label', {timeout: 7000});
            return true;
          } catch (e36652234) {
              console.log(e36652234)
            console.log("Checkout page waiting for too long!");
            //await page.screenshot({path: 'screenshots/toolongcheckout.png', fullPage: true});
            return false;
          }
    
}

    async function subtotal() {
        //Calculate total $$$ dumped
    checkoutAmount = await page.evaluate(() => document.querySelector('html > body > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(2) > main > div > div:nth-of-type(2) > form > div:nth-of-type(2) > div:nth-of-type(4) > div:nth-of-type(2) > p:nth-of-type(1)').textContent);
    console.log('Subtotal: ' + checkoutAmount);
    return checkoutAmount;
    }

    async function repeatNetworkErr(sendItemUrl) {
        try {
            await page.goto(sendItemUrl, {"waitUntil" : "networkidle0", timeout: 10000});
          } catch (e) {
            repeatNetworkErr(sendItemUrl)
          }
    }

    async function addNewItem(itemUrl) {
       try {
        console.log("loading: " + itemUrl);
        await repeatNetworkErr(itemUrl);
        console.log("went to " + itemUrl);
       //await page.screenshot({path: 'screenshots/trump1.png', fullPage: true});
        //number of items selection dropdown click
        try {
            await page.waitForSelector('#shopify-section-product > main > div.vp-80 > div > div.product-detail > form > div.info > div.product-options > div > div > span > span.selection > span > span.select2-selection__arrow');

          } catch {
              //if dropdown on product screen doesn't load, reload and start over...
            console.log('not found');
            await addNewItem(itemUrl);

            return;
          }

          await page.click("#shopify-section-product > main > div.vp-80 > div > div.product-detail > form > div.info > div.product-options > div > div > span > span.selection > span > span.select2-selection__arrow");

            console.log("dropdown selection clicked");
        //await page.screenshot({path: 'screenshots/trump2.png', fullPage: true});
        //Maximum number of item in cart
        try {
            await page.waitForSelector('html > body > span > span > span:nth-of-type(2) > ul > li:last-child');

          } catch {
              //if last elem dropdown on product screen doesn't load, reload and start over...
            console.log('not found');
            await addNewItem(itemUrl);

            return;
          }


        await page.click("html > body > span > span > span:nth-of-type(2) > ul > li:last-child")
        console.log("clicked last child")
        //await page.screenshot({path: 'screenshots/trump3.png', fullPage: true});
        //Click add to cart
        await page.click("html > body > div:nth-of-type(1) > div:nth-of-type(2) > div > main > div:nth-of-type(1) > div > div:nth-of-type(1) > form > div:nth-of-type(2) > div:nth-of-type(3) > button")
        console.log("clicked checkout")
        //await page.screenshot({path: 'screenshots/trump1.png', fullPage: true});
        //await page.screenshot({path: 'screenshots/trump4.png', fullPage: true});
        try {
            await page.waitForNavigation({ waitUntil: 'networkidle0', timeout:20000});

          } catch {
              //if checkout screen doesn't load, reload and start over...
            console.log('checkout not loading, skip');
            //await addNewItem(itemUrl);

            return;
          }
        
        if(await waitForCheckoutPage()) {await subtotal();} else {
            //await addNewItem(itemUrl)
        
        return;
        };
        
        //await page.waitForNavigation({ waitUntil: 'networkidle0' });
       } catch (e) {
            console.log("Error! noooooo");
            console.log(e);
            console.log('trying again...');
            await addNewItem(itemUrl);
            return;
       }
    }

      await addNewItem("https://shop.donaldjtrump.com/products/america-first-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/official-make-america-great-again-45th-president-hat-red");
      await addNewItem("https://shop.donaldjtrump.com/products/official-make-america-great-again-45th-president-hat-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/official-make-america-great-again-45th-president-hat-white");
      await addNewItem("https://shop.donaldjtrump.com/products/babies-lives-matter");
      await addNewItem("https://shop.donaldjtrump.com/products/blue-camo-maga-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/defend-the-police-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/defend-the-police-bumper-stickers-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-dad-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/make-space-great-again-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/make-space-great-again-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/youaintblack-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/limited-edition-boaters-for-trump-hat-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/memorial-day-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/israeli-keep-america-great-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-coloring-book");
      await addNewItem("https://shop.donaldjtrump.com/products/official-keep-america-great-45th-president-hat-white-gold");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-flag-red");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-flag-blue");
      await addNewItem("https://shop.donaldjtrump.com/products/boaters-for-trump-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mama-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mama-maga-babe-hats-white");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mama-maga-babe-hats-black");
      await addNewItem("https://shop.donaldjtrump.com/products/moms-for-trump-rally-sign-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-puzzle");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-hoodie-red-1");
      await addNewItem("https://shop.donaldjtrump.com/products/cops-for-trump-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-grey-2");
      await addNewItem("https://shop.donaldjtrump.com/products/official-keep-america-great-45th-president-hat-white");
      await addNewItem("https://shop.donaldjtrump.com/products/i-heart-trump-straws-pack-of-10");
      await addNewItem("https://shop.donaldjtrump.com/products/freedom-2020-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/irish-americans-for-trump-pint-glasses-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/official-keep-america-great-45th-president-hat-camo");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-hoodie-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-keep-america-great-winter-hat-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-love-wine-glasses-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/limited-edition-irish-americans-for-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-luck-of-the-irish-whiskey-glasses-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/st-paddys-2020-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/i-heart-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/i-heart-trump-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/i-heart-trump-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-45th-president-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/impeach-this-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/greek-keep-america-great-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/babies-for-trump-infant-one-piece-red");
      await addNewItem("https://shop.donaldjtrump.com/products/official-donald-j-trump-keep-america-great-2020-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-collectible-ornament");
      await addNewItem("https://shop.donaldjtrump.com/products/i-cry-less-than-a-democrat-infant-one-piece");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-gift-wrapping-paper");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-christmas-sweater-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-snowflake-gift-wrapping-paper");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-wood-train-set");
      await addNewItem("https://shop.donaldjtrump.com/products/babies-for-trump-infant-one-piece-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-wood-semi-truck");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-merry-christmas-gift-wrapping-paper");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-mug-red");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-cuff-links");
      await addNewItem("https://shop.donaldjtrump.com/products/babies-for-trump-infant-one-piece-white");
      await addNewItem("https://shop.donaldjtrump.com/products/black-voices-for-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/get-over-it-tee-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/usa-camo-dog-bandana");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2020-tonal-tee-olive-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-long-sleeve-tee-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/cops-for-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/american-worker-hat-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/donald-j-trump-limited-edition-fine-art-print");
      await addNewItem("https://shop.donaldjtrump.com/products/official-donald-trump-fine-point-marker");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-white-2");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-2020-cap-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/cops-for-trump-rally-sign-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-straws");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-navy-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-2020-photo-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-black-2");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-yard-sign-blue-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/latinos-for-trump-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-v-neck-tee-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-mug-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-long-sleeve-tee-white-3");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-playing-cards");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-maga-mens-dry-wicking-polo-red-1");
      await addNewItem("https://shop.donaldjtrump.com/products/four-more-years-tee-white");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-bumper-sticker-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-stadium-cups-pack-of-6");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-rally-signs-blue-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-campaign-buttons-white-set-of-3");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-bumper-sticker-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/latinos-for-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/latinos-for-trump-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-window-cling-white-set-of-5");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-cup-set-of-5");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-v-neck-tee-pink");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-ball-cap-red-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-2020-rally-signs-white-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-yard-sign-white-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-youth-tee-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-pint-glass-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-infant-one-piece-white-1");
      await addNewItem("https://shop.donaldjtrump.com/products/official-maga-2020-cap-red");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-rally-sign-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-kag-womens-dry-wicking-polo-white");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-beverage-coolers-pack-of-6");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-window-decal-set-of-4");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-2020-rally-signs-red-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-mug-white-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-ball-cap-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-window-cling-black-set-of-5");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-camo-hat-breakup");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-long-sleeve-tee-grey-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-infant-one-piece-pink-1");
      await addNewItem("https://shop.donaldjtrump.com/products/latinos-for-trump-rally-sign-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/latinos-for-trump-bumper-sticker-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2020-tonal-tee-natural");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2020-tee-red-1");
      await addNewItem("https://shop.donaldjtrump.com/products/drain-the-swamp-2020-bumper-stickers-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/space-force-bumper-stickers-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-freedom-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-keep-america-great-pet-leash");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-keep-america-great-dog-collar");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-working-rally-sign-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/woke-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/black-voices-for-trump-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/black-voices-for-trump-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/black-voices-for-trump-rally-sign-white-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-keep-america-great-pullover-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-rally-sign-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-tee-white-1");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-tonal-tee-olive");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-lapel-pin-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/stop-the-impeachment-limited-edition-decal-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-bumper-sticker-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/border-wall-construction-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-aint-a-mistake-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-aint-a-mistake-tee-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/it-aint-a-mistake-voting-demographic-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/if-you-dont-like-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/the-44-didnt-work-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/bull-schiff-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-cuff-links-gold");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-metallic-hat-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mama-hat-black");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-babe-hat-black");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-babe-hat-white");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mama-hat-white");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-patriotic-2020-beverage-coolers-set-of-6");
      await addNewItem("https://shop.donaldjtrump.com/products/workers-for-trump-hard-hat-decals-pack-of-10");
      await addNewItem("https://shop.donaldjtrump.com/products/official-keep-america-great-45th-president-hat-navy-gold");
      await addNewItem("https://shop.donaldjtrump.com/products/black-voices-for-trump-hoodie");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-dad-whiskey-glasses-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-dad-pint-glasses-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/asian-pacific-american-for-trump-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/copy-of-asian-pacific-americans-for-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pride-2020-ringer-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-keep-america-great-pride-ringer-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/make-america-great-again-2020-price-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/polish-americans-for-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/polish-americans-for-trump-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/polish-make-america-great-again-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/buildthewall-mens-ss-t-shirt-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/buildthewall-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/youaintblack-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/youaintblack-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/america-first-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/america-first-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/american-worker-hat-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/asian-pacific-american-for-trump-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/copy-of-asian-pacific-americans-for-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/babies-for-trump-infant-one-piece-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/babies-for-trump-infant-one-piece-red");
      await addNewItem("https://shop.donaldjtrump.com/products/babies-for-trump-infant-one-piece-white");
      await addNewItem("https://shop.donaldjtrump.com/products/black-voices-for-trump-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/black-voices-for-trump-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/black-voices-for-trump-hoodie");
      await addNewItem("https://shop.donaldjtrump.com/products/black-voices-for-trump-rally-sign-white-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/black-voices-for-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/black-voices-for-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/blue-camo-maga-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/border-wall-construction-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/border-wall-construction-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/build-the-wall-crime-will-fall-bumper-sticker-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/bull-schiff-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/bull-schiff-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/cops-for-trump-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/cops-for-trump-rally-sign-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/cops-for-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/cops-for-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/defend-the-police-bumper-stickers-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/defend-the-police-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/defend-the-police-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/official-donald-j-trump-keep-america-great-2020-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/donald-j-trump-limited-edition-fine-art-print");
      await addNewItem("https://shop.donaldjtrump.com/products/donation");
      await addNewItem("https://shop.donaldjtrump.com/products/drain-the-swamp-2020-bumper-stickers-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/firefighters-for-trump-and-law-enforcement-for-trump-hat-bundle");
      await addNewItem("https://shop.donaldjtrump.com/products/firefighters-for-trump-hat-black");
      await addNewItem("https://shop.donaldjtrump.com/products/four-more-years-tee-white");
      await addNewItem("https://shop.donaldjtrump.com/products/four-more-years-tee-white-1");
      await addNewItem("https://shop.donaldjtrump.com/products/freedom-2020-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/get-over-it-tee-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/get-over-it-tee-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/greek-keep-america-great-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/i-heart-trump-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/i-heart-trump-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/i-heart-trump-straws-pack-of-10");
      await addNewItem("https://shop.donaldjtrump.com/products/i-heart-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/i-heart-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/if-you-dont-like-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/if-you-dont-like-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/impeach-this-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/impeach-this-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/irish-americans-for-trump-pint-glasses-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/israeli-keep-america-great-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/it-aint-a-mistake-voting-demographic-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/it-aint-a-mistake-voting-demographic-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-collectible-ornament");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-freedom-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-hoodie-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-hoodie-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-hoodie-red");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-hoodie-red-1");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-christmas-sweater");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-christmas-sweater-1");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-working-rally-sign-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/latinos-for-trump-bumper-sticker-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/latinos-for-trump-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/latinos-for-trump-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/latinos-for-trump-rally-sign-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/latinos-for-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/latinos-for-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/law-enforcement-for-trump-hat-black");
      await addNewItem("https://shop.donaldjtrump.com/products/babies-lives-matter");
      await addNewItem("https://shop.donaldjtrump.com/products/limited-edition-boaters-for-trump-hat-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/boaters-for-trump-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/i-cry-less-than-a-democrat-infant-one-piece");
      await addNewItem("https://shop.donaldjtrump.com/products/limited-edition-irish-americans-for-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/limited-edition-irish-americans-for-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/memorial-day-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/memorial-day-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-babe-hat-black");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-babe-hat-white");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-dad-pint-glasses-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-dad-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-dad-whiskey-glasses-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-pet-collar");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mama-maga-babe-hats-black");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mama-maga-babe-hats-white");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mama-hat-black");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mama-hat-white");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mama-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mens-swim-shorts");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mesh-hat-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mesh-hat-red");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mesh-hat-white-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-pet-leash");
      await addNewItem("https://shop.donaldjtrump.com/products/make-america-great-again-2020-price-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/make-america-great-again-pride-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/make-america-great-again-pride-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/make-our-farmers-great-again-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/make-space-great-again-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/make-space-great-again-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/make-space-great-again-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/moms-for-trump-rally-sign-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/official-donald-trump-fine-point-marker");
      await addNewItem("https://shop.donaldjtrump.com/products/official-donald-trump-make-america-great-again-cap-orange-camo");
      await addNewItem("https://shop.donaldjtrump.com/products/official-donald-trump-make-america-great-again-hat-pink");
      await addNewItem("https://shop.donaldjtrump.com/products/official-donald-trump-make-america-great-again-cap-red");
      await addNewItem("https://shop.donaldjtrump.com/products/official-donald-trump-make-america-great-again-hat-navy-white");
      await addNewItem("https://shop.donaldjtrump.com/products/official-inauguration-short-sleeve-tee-white");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-45th-president-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/official-keep-america-great-45th-president-hat-camo");
      await addNewItem("https://shop.donaldjtrump.com/products/official-keep-america-great-45th-president-hat-navy-gold");
      await addNewItem("https://shop.donaldjtrump.com/products/official-keep-america-great-45th-president-hat-white");
      await addNewItem("https://shop.donaldjtrump.com/products/official-keep-america-great-45th-president-hat-white-gold");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-2020-cap-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/official-maga-2020-cap-red");
      await addNewItem("https://shop.donaldjtrump.com/products/official-make-america-great-again-45th-president-hat-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/official-make-america-great-again-45th-president-hat-red");
      await addNewItem("https://shop.donaldjtrump.com/products/official-make-america-great-again-45th-president-hat-white");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2020-tee-red-1");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2020-tee-red");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2020-tonal-tee-natural");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2020-tonal-tee-natural-1");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2020-tonal-tee-olive-1");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2020-tonal-tee-olive");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-coloring-book");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-make-america-great-again-bumper-sticker-pack-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-cuff-links-gold");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-cuff-links");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-lapel-pin-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-puzzle");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2016-mens-short-sleeve-t-shirt-black");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2016-mens-short-sleeve-t-shirt-white");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-beverage-coolers-pack-of-6");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-bumper-sticker-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-campaign-buttons-white-set-of-3");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-flag-blue");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-flag-red");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-mug-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-mug-red");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-mug-white-1");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-rally-signs-blue-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-stadium-cups-pack-of-6");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-window-cling-black-set-of-5");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-window-cling-white-set-of-5");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-yard-sign-blue-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-yard-sign-white-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-mini-megaphones-red-blue-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-presidential-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/official-usa-45th-presidential-cap-camo");
      await addNewItem("https://shop.donaldjtrump.com/products/official-usa-45th-presidential-hat-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/official-usa-45th-presidential-cap-red");
      await addNewItem("https://shop.donaldjtrump.com/products/official-usa-45th-presidential-hat-white");
      await addNewItem("https://shop.donaldjtrump.com/products/official-usa-thank-you-tour-2016-short-sleeve-tee-navy-small");
      await addNewItem("https://shop.donaldjtrump.com/products/official-usa-thank-you-tour-2016-short-sleeve-tee-white-small");
      await addNewItem("https://shop.donaldjtrump.com/products/official-mr-pencil-neck-limited-edition-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/pencil-neck-adam-schiff-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/polish-americans-for-trump-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/polish-americans-for-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/polish-americans-for-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/polish-make-america-great-again-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/space-force-bumper-stickers-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/space-force-raglan-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/space-force-raglan-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/st-paddys-2020-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/stand-up-for-america-mens-football-jersey");
      await addNewItem("https://shop.donaldjtrump.com/products/stop-the-impeachment-limited-edition-decal-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/team-trump-2016-mens-short-sleeve-t-shirt-white");
      await addNewItem("https://shop.donaldjtrump.com/products/team-trump-2016-womens-form-fitting-short-sleeve-t-shirt-white");
      await addNewItem("https://shop.donaldjtrump.com/products/team-trump-2016-youth-short-sleeve-t-shirt-white");
      await addNewItem("https://shop.donaldjtrump.com/products/test");
      await addNewItem("https://shop.donaldjtrump.com/products/the-44-didnt-work-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/the-44-didnt-work-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-2020-photo-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-2020-rally-signs-red-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-2020-rally-signs-white-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-aint-a-mistake-tee-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-aint-a-mistake-tee-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-aint-a-mistake-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-aint-a-mistake-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-gift-wrapping-paper");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-keep-america-great-pullover-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-keep-america-great-pullover-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-keep-america-great-winter-hat-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-love-wine-glasses-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-luck-of-the-irish-whiskey-glasses-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-keep-america-great-pride-ringer-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-wood-semi-truck");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-wood-train-set");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-keep-america-great-dog-collar");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-keep-america-great-pet-leash");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-merry-christmas-gift-wrapping-paper");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-pet-leash");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-snowflake-gift-wrapping-paper");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pride-2020-ringer-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-straws");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-ball-cap-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-ball-cap-red-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-camo-hat-breakup");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-cup-set-of-5");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-infant-one-piece-pink-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-infant-one-piece-white-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-long-sleeve-tee-grey-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-long-sleeve-tee-grey-3");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-long-sleeve-tee-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-long-sleeve-tee-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-long-sleeve-tee-white-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-long-sleeve-tee-white-3");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-pint-glass-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-playing-cards");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-black-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-black-3");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-grey-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-grey-3");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-navy-3");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-navy-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-white-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-white-3");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-window-decal-set-of-4");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-youth-tee-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-45-tee-grey");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-45-tee-grey-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-45-tee-white");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-maga-mens-dry-wicking-polo-red-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-kag-mens-dry-wicking-polo-white");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-maga-womens-dry-wicking-polo-red-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-kag-womens-dry-wicking-polo-white");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-make-america-great-again-mens-long-sleeve-t-shirt-white");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-make-america-great-again-mens-short-sleeve-t-shirt-black");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-make-america-great-again-womens-short-sleeve-t-shirt-white");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-patriotic-2020-beverage-coolers-set-of-6");
      await addNewItem("https://shop.donaldjtrump.com/products/usa-camo-dog-bandana");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-bumper-sticker-pack-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-bumper-sticker-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-mens-short-sleeve-t-shirt-white");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-rally-sign-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-mens-tshirt-gray");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-tee-white-1");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-tee-white");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-tonal-tee-olive");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-tonal-tee-olive-1");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-womens-form-fitting-short-sleeve-t-shirt-white");
      await addNewItem("https://shop.donaldjtrump.com/products/woke-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-bumper-sticker-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-metallic-hat-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-rally-sign-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-v-neck-tee-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-v-neck-tee-pink");
      await addNewItem("https://shop.donaldjtrump.com/products/workers-for-trump-hard-hat-decals-pack-of-10");
      await addNewItem("https://shop.donaldjtrump.com/products/i-am-your-voice-bumper-stickers-set-of-3");
      await addNewItem("https://shop.donaldjtrump.com/products/america-first-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/babies-lives-matter");
      await addNewItem("https://shop.donaldjtrump.com/products/defend-the-police-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pride-2020-ringer-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-keep-america-great-pride-ringer-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-dad-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/youaintblack-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/memorial-day-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/black-voices-for-trump-hoodie");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mama-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/copy-of-asian-pacific-americans-for-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/i-heart-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/border-wall-construction-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/impeach-this-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/i-cry-less-than-a-democrat-infant-one-piece");
      await addNewItem("https://shop.donaldjtrump.com/products/bull-schiff-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/if-you-dont-like-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-aint-a-mistake-tee-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/babies-for-trump-infant-one-piece-red");
      await addNewItem("https://shop.donaldjtrump.com/products/limited-edition-irish-americans-for-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/the-44-didnt-work-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-aint-a-mistake-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/it-aint-a-mistake-voting-demographic-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/america-first-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-christmas-sweater");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-long-sleeve-tee-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-tee-white-1");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-hoodie-red");
      await addNewItem("https://shop.donaldjtrump.com/products/babies-for-trump-infant-one-piece-white");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2020-tonal-tee-natural");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2020-tee-red-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-keep-america-great-pullover-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2020-tonal-tee-natural-1");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-hoodie-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2020-tonal-tee-olive-1");
      await addNewItem("https://shop.donaldjtrump.com/products/babies-for-trump-infant-one-piece-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-tee-white");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-hoodie-red-1");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-tonal-tee-olive");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-hoodie-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-christmas-sweater-1");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2020-tonal-tee-olive");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-long-sleeve-tee-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2020-tee-red");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-tonal-tee-olive-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-keep-america-great-pullover-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/cops-for-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/get-over-it-tee-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-grey-3");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-navy-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-maga-mens-dry-wicking-polo-red-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-white-2");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-v-neck-tee-pink");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-long-sleeve-tee-white-3");
      await addNewItem("https://shop.donaldjtrump.com/products/four-more-years-tee-white");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-navy-3");
      await addNewItem("https://shop.donaldjtrump.com/products/latinos-for-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-v-neck-tee-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-kag-womens-dry-wicking-polo-white");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-youth-tee-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-long-sleeve-tee-grey-2");
      await addNewItem("https://shop.donaldjtrump.com/products/latinos-for-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-black-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-infant-one-piece-pink-1");
      await addNewItem("https://shop.donaldjtrump.com/products/four-more-years-tee-white-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-grey-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-white-3");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-maga-womens-dry-wicking-polo-red-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-black-3");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-long-sleeve-tee-grey-3");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-infant-one-piece-white-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-kag-mens-dry-wicking-polo-white");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-long-sleeve-tee-white-2");
      await addNewItem("https://shop.donaldjtrump.com/products/stand-up-for-america-mens-football-jersey");
      await addNewItem("https://shop.donaldjtrump.com/products/buildthewall-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/space-force-raglan-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/cops-for-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/make-america-great-again-pride-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/make-america-great-again-pride-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/buildthewall-mens-ss-t-shirt-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/pencil-neck-adam-schiff-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/get-over-it-tee-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/black-voices-for-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/black-voices-for-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/border-wall-construction-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-aint-a-mistake-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-aint-a-mistake-tee-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/it-aint-a-mistake-voting-demographic-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/if-you-dont-like-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/the-44-didnt-work-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/bull-schiff-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/impeach-this-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/i-heart-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/limited-edition-irish-americans-for-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/memorial-day-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/youaintblack-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/make-space-great-again-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/make-space-great-again-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/defend-the-police-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/polish-americans-for-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/polish-americans-for-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/america-first-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/polish-americans-for-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/defend-the-police-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-dad-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pride-2020-ringer-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-keep-america-great-pride-ringer-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/make-space-great-again-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/youaintblack-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/memorial-day-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/black-voices-for-trump-hoodie");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/the-44-didnt-work-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/impeach-this-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/it-aint-a-mistake-voting-demographic-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/limited-edition-irish-americans-for-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/official-mr-pencil-neck-limited-edition-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/bull-schiff-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/i-heart-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-aint-a-mistake-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-tonal-tee-olive");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2020-tonal-tee-natural");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-christmas-sweater");
      await addNewItem("https://shop.donaldjtrump.com/products/border-wall-construction-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-aint-a-mistake-tee-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/if-you-dont-like-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2020-tonal-tee-olive");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-long-sleeve-tee-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-tee-white");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-hoodie-red");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-hoodie-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2020-tee-red");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-keep-america-great-pullover-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/get-over-it-tee-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/cops-for-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-white-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-black-2");
      await addNewItem("https://shop.donaldjtrump.com/products/four-more-years-tee-white-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-maga-mens-dry-wicking-polo-red-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-long-sleeve-tee-white-3");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-grey-3");
      await addNewItem("https://shop.donaldjtrump.com/products/latinos-for-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-navy-3");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-kag-mens-dry-wicking-polo-white");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-long-sleeve-tee-grey-3");
      await addNewItem("https://shop.donaldjtrump.com/products/buildthewall-mens-ss-t-shirt-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/space-force-raglan-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/stand-up-for-america-mens-football-jersey");
      await addNewItem("https://shop.donaldjtrump.com/products/make-america-great-again-pride-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/black-voices-for-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/america-first-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/polish-americans-for-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/defend-the-police-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/make-space-great-again-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/youaintblack-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/memorial-day-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/copy-of-asian-pacific-americans-for-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mama-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/it-aint-a-mistake-voting-demographic-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/i-heart-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/impeach-this-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/bull-schiff-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2020-tonal-tee-olive-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-aint-a-mistake-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/the-44-didnt-work-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/border-wall-construction-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2020-tonal-tee-natural-1");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-christmas-sweater-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-aint-a-mistake-tee-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/if-you-dont-like-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/black-voices-for-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/limited-edition-irish-americans-for-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-hoodie-red-1");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-tee-white-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-long-sleeve-tee-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2020-tee-red-1");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-tonal-tee-olive-1");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-hoodie-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-keep-america-great-pullover-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/get-over-it-tee-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/cops-for-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-v-neck-tee-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-maga-womens-dry-wicking-polo-red-1");
      await addNewItem("https://shop.donaldjtrump.com/products/four-more-years-tee-white");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-white-3");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-grey-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-black-3");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-tee-navy-2");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-v-neck-tee-pink");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-long-sleeve-tee-white-2");
      await addNewItem("https://shop.donaldjtrump.com/products/latinos-for-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-kag-womens-dry-wicking-polo-white");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-long-sleeve-tee-grey-2");
      await addNewItem("https://shop.donaldjtrump.com/products/space-force-raglan-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/buildthewall-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/make-america-great-again-pride-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/pencil-neck-adam-schiff-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-keep-america-great-pride-ringer-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pride-2020-ringer-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-v-neck-tee-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-tonal-tee-olive");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-v-neck-tee-pink");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/woke-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-bumper-sticker-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-bumper-sticker-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/babies-for-trump-infant-one-piece-red");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/babies-for-trump-infant-one-piece-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/law-enforcement-for-trump-hat-black");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-rally-sign-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-tee-white");
      await addNewItem("https://shop.donaldjtrump.com/products/greek-keep-america-great-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/latinos-for-trump-bumper-sticker-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-rally-sign-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/workers-for-trump-hard-hat-decals-pack-of-10");
      await addNewItem("https://shop.donaldjtrump.com/products/irish-americans-for-trump-pint-glasses-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/firefighters-for-trump-hat-black");
      await addNewItem("https://shop.donaldjtrump.com/products/latinos-for-trump-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/babies-for-trump-infant-one-piece-white");
      await addNewItem("https://shop.donaldjtrump.com/products/cops-for-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/latinos-for-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/cops-for-trump-rally-sign-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/limited-edition-irish-americans-for-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/limited-edition-irish-americans-for-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/latinos-for-trump-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-tonal-tee-olive-1");
      await addNewItem("https://shop.donaldjtrump.com/products/latinos-for-trump-rally-sign-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/black-voices-for-trump-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-tee-white-1");
      await addNewItem("https://shop.donaldjtrump.com/products/latinos-for-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/firefighters-for-trump-and-law-enforcement-for-trump-hat-bundle");
      await addNewItem("https://shop.donaldjtrump.com/products/black-voices-for-trump-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/black-voices-for-trump-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/cops-for-trump-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/cops-for-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/black-voices-for-trump-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/black-voices-for-trump-rally-sign-white-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mesh-hat-red");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-make-america-great-again-bumper-sticker-pack-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2016-mens-short-sleeve-t-shirt-black");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-mens-tshirt-gray");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-presidential-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-bumper-sticker-pack-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mesh-hat-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/official-inauguration-short-sleeve-tee-white");
      await addNewItem("https://shop.donaldjtrump.com/products/official-usa-thank-you-tour-2016-short-sleeve-tee-navy-small");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mesh-hat-white-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2016-mens-short-sleeve-t-shirt-white");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mens-swim-shorts");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-make-america-great-again-mens-short-sleeve-t-shirt-black");
      await addNewItem("https://shop.donaldjtrump.com/products/i-am-your-voice-bumper-stickers-set-of-3");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-45-tee-grey");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-make-america-great-again-mens-long-sleeve-t-shirt-white");
      await addNewItem("https://shop.donaldjtrump.com/products/official-usa-thank-you-tour-2016-short-sleeve-tee-white-small");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-mens-short-sleeve-t-shirt-white");
      await addNewItem("https://shop.donaldjtrump.com/products/team-trump-2016-mens-short-sleeve-t-shirt-white");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-pet-leash");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-make-america-great-again-womens-short-sleeve-t-shirt-white");
      await addNewItem("https://shop.donaldjtrump.com/products/team-trump-2016-womens-form-fitting-short-sleeve-t-shirt-white");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-womens-form-fitting-short-sleeve-t-shirt-white");
      await addNewItem("https://shop.donaldjtrump.com/products/team-trump-2016-youth-short-sleeve-t-shirt-white");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-45-tee-white");
      await addNewItem("https://shop.donaldjtrump.com/products/polish-americans-for-trump-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-dad-whiskey-glasses-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-dad-pint-glasses-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-flag-blue");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-campaign-buttons-white-set-of-3");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-flag-red");
      await addNewItem("https://shop.donaldjtrump.com/products/asian-pacific-american-for-trump-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-patriotic-2020-beverage-coolers-set-of-6");
      await addNewItem("https://shop.donaldjtrump.com/products/i-heart-trump-straws-pack-of-10");
      await addNewItem("https://shop.donaldjtrump.com/products/workers-for-trump-hard-hat-decals-pack-of-10");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-coloring-book");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-puzzle");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-love-wine-glasses-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-2020-photo-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/i-heart-trump-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-luck-of-the-irish-whiskey-glasses-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-collectible-ornament");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-gift-wrapping-paper");
      await addNewItem("https://shop.donaldjtrump.com/products/irish-americans-for-trump-pint-glasses-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-wood-semi-truck");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-snowflake-gift-wrapping-paper");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-wood-train-set");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-cuff-links");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-merry-christmas-gift-wrapping-paper");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-mug-red");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-lapel-pin-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-keep-america-great-dog-collar");
      await addNewItem("https://shop.donaldjtrump.com/products/usa-camo-dog-bandana");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-keep-america-great-pet-leash");
      await addNewItem("https://shop.donaldjtrump.com/products/black-voices-for-trump-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-mug-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/official-donald-trump-fine-point-marker");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-pint-glass-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/donald-j-trump-limited-edition-fine-art-print");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-straws");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-mug-white-1");
      await addNewItem("https://shop.donaldjtrump.com/products/latinos-for-trump-buttons-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-beverage-coolers-pack-of-6");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-stadium-cups-pack-of-6");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-cup-set-of-5");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-playing-cards");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-pet-collar");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-pet-leash");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-cuff-links-gold");
      await addNewItem("https://shop.donaldjtrump.com/products/official-make-america-great-again-45th-president-hat-red");
      await addNewItem("https://shop.donaldjtrump.com/products/official-make-america-great-again-45th-president-hat-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/official-make-america-great-again-45th-president-hat-white");
      await addNewItem("https://shop.donaldjtrump.com/products/make-america-great-again-2020-price-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/blue-camo-maga-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/polish-make-america-great-again-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/make-space-great-again-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/official-keep-america-great-45th-president-hat-navy-gold");
      await addNewItem("https://shop.donaldjtrump.com/products/boaters-for-trump-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/israeli-keep-america-great-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/official-donald-j-trump-keep-america-great-2020-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/limited-edition-boaters-for-trump-hat-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/freedom-2020-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/official-keep-america-great-45th-president-hat-white-gold");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mama-maga-babe-hats-white");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mama-hat-white");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-babe-hat-white");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-babe-hat-black");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mama-hat-black");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mama-maga-babe-hats-black");
      await addNewItem("https://shop.donaldjtrump.com/products/official-keep-america-great-45th-president-hat-camo");
      await addNewItem("https://shop.donaldjtrump.com/products/official-keep-america-great-45th-president-hat-white");
      await addNewItem("https://shop.donaldjtrump.com/products/official-usa-45th-presidential-cap-red");
      await addNewItem("https://shop.donaldjtrump.com/products/official-usa-45th-presidential-hat-white");
      await addNewItem("https://shop.donaldjtrump.com/products/official-usa-45th-presidential-hat-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-45th-president-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-keep-america-great-winter-hat-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/i-heart-trump-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/st-paddys-2020-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/black-voices-for-trump-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/cops-for-trump-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/official-donald-trump-make-america-great-again-cap-red");
      await addNewItem("https://shop.donaldjtrump.com/products/greek-keep-america-great-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-metallic-hat-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/american-worker-hat-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-ball-cap-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/woke-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/law-enforcement-for-trump-hat-black");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-2020-cap-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-ball-cap-red-1");
      await addNewItem("https://shop.donaldjtrump.com/products/official-maga-2020-cap-red");
      await addNewItem("https://shop.donaldjtrump.com/products/latinos-for-trump-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-camo-hat-breakup");
      await addNewItem("https://shop.donaldjtrump.com/products/official-donald-trump-make-america-great-again-hat-pink");
      await addNewItem("https://shop.donaldjtrump.com/products/firefighters-for-trump-hat-black");
      await addNewItem("https://shop.donaldjtrump.com/products/make-our-farmers-great-again-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/firefighters-for-trump-and-law-enforcement-for-trump-hat-bundle");
      await addNewItem("https://shop.donaldjtrump.com/products/official-donald-trump-make-america-great-again-hat-navy-white");
      await addNewItem("https://shop.donaldjtrump.com/products/official-donald-trump-make-america-great-again-cap-orange-camo");
      await addNewItem("https://shop.donaldjtrump.com/products/official-usa-45th-presidential-cap-camo");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mesh-hat-red");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mesh-hat-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mesh-hat-white-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-freedom-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-45th-president-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/official-donald-j-trump-keep-america-great-2020-hat");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-mesh-hat-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-hoodie-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-hoodie-red");
      await addNewItem("https://shop.donaldjtrump.com/products/american-worker-hat-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-keep-america-great-pullover-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2020-tonal-tee-olive-1");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2020-tonal-tee-olive");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-hoodie-red-1");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2020-tee-red");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-tee");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2020-tee-red-1");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-hoodie-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-keep-america-great-pullover-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2020-tonal-tee-natural");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-2020-tonal-tee-natural-1");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-working-rally-sign-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-tee-1");
      await addNewItem("https://shop.donaldjtrump.com/products/four-more-years-tee-white-1");
      await addNewItem("https://shop.donaldjtrump.com/products/four-more-years-tee-white");
      await addNewItem("https://shop.donaldjtrump.com/products/defend-the-police-bumper-stickers-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/moms-for-trump-rally-sign-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/workers-for-trump-hard-hat-decals-pack-of-10");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-rally-sign-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-window-decal-set-of-4");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-working-rally-sign-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-bumper-sticker-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/veterans-for-trump-rally-sign-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/black-voices-for-trump-rally-sign-white-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-bumper-sticker-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-2020-rally-signs-white-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-window-cling-black-set-of-5");
      await addNewItem("https://shop.donaldjtrump.com/products/latinos-for-trump-bumper-sticker-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-yard-sign-white-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-window-cling-white-set-of-5");
      await addNewItem("https://shop.donaldjtrump.com/products/latinos-for-trump-rally-sign-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/official-trump-pence-2020-rally-signs-blue-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/women-for-trump-bumper-sticker-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/cops-for-trump-rally-sign-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-2020-rally-signs-red-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/build-the-wall-crime-will-fall-bumper-sticker-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/drain-the-swamp-2020-bumper-stickers-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/space-force-bumper-stickers-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/stop-the-impeachment-limited-edition-decal-set-of-2");
      await addNewItem("https://shop.donaldjtrump.com/products/babies-lives-matter");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-babe-hat-black");
      await addNewItem("https://shop.donaldjtrump.com/products/babies-for-trump-infant-one-piece-red");
      await addNewItem("https://shop.donaldjtrump.com/products/i-cry-less-than-a-democrat-infant-one-piece");
      await addNewItem("https://shop.donaldjtrump.com/products/babies-for-trump-infant-one-piece-navy");
      await addNewItem("https://shop.donaldjtrump.com/products/maga-babe-hat-white");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-youth-tee-navy-1");
      await addNewItem("https://shop.donaldjtrump.com/products/babies-for-trump-infant-one-piece-white");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-infant-one-piece-white-1");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-wood-semi-truck");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-wood-train-set");
      await addNewItem("https://shop.donaldjtrump.com/products/trump-pence-2020-infant-one-piece-pink-1");
      await addNewItem("https://shop.donaldjtrump.com/products/keep-america-great-collectible-ornament");
    //Additional $25 contribution
    
    //await page.click("html > body > div:nth-of-type(1) > div:nth-of-type(2) > div:nth-of-type(2) > main > div > div:nth-of-type(2) > form > div:nth-of-type(2) > div:nth-of-type(2) > div > div > div:nth-of-type(4) > input");

    await subtotal();
    await page.screenshot({path: 'screenshots/trump' + Date.now() + '.png', fullPage: true});
    console.log("Dumping Cart...")
    await browser.close();
    console.log("Cart Dumped Successfully")
}
run();